data_dir: data/processed
output_figures: outputs/figures
output_models: outputs/models
seed: 4881
cores: 4

survey_data_path: data/processed/fair_survey_clean.rds

debug: true
echo: false
warning: false

palette: 
  - "#0072B2"
  - "#666666"
  - "#D55E00"
